/** BE VERY VERY CAREFUL WHEN YOU CHANGE THESE */
const HOME_VIEW_HANDLER_EVENT_ID = 'app_home_opened';
const FEEDBACK_BTN_HANDLER_ACTION_ID = 'quirkback_button_click';
const HOME_EMOJI_BTN_HANDLER_ACTION_ID = 'emoji_button_click';
const HOME_LETTERS_BTN_HANDLER_ACTION_ID = 'letters_button_click';
const TRIGGER_EMOJI_MODAL_CALLBACK_ID = 'TRIGGER_EMOJI_GAME_MODAL';
const TRIGGER_LETTERS_MODAL_CALLBACK_ID = 'TRIGGER_LETTERS_GAME_MODAL';
const HAPPY_HOURS_SLASH_COMMAND_ID = '/happy';
const EMOJI_GUESS_BUTTON_ACTION_ID = 'emoji_guess_btn_click';
const LETTERS_ANSWER_BUTTON_ACTION_ID = 'letters_answer_btn_click';
const EMOJI_GUESS_MODAL_SUBMISSION_CALLBACK_ID = 'emoji_guess_modal';
const LETTERS_ANSWER_MODAL_SUBMISSION_CALLBACK_ID = 'letters_answer_modal';
const INVITE_APP_TO_CHANNEL_ACTION_ID = 'invite-app-to-channel-button';
const ADD_APP_TO_CHANNEL_CALLBACK_ID = 'ADD_TO_CHANNEL';
const SHORTCUT_EMOJI_CALLBACK_ID = 'SHORTCUT_START_EMOJI';
const SHORTCUT_LETTERS_CALLBACK_ID = 'SHORTCUT_START_LETTERS';
const GAME_STATUS_CREATED = 'CREATED';
const GAME_STATUS_COMPLETED = 'COMPLETED';
const GAME_TYPE_EMOJI = 'EMOJI';
const GAME_TYPE_LETTERS = 'LETTERS';

const CHANNEL_ACTION_ID = 'action_channel_id';
const QUESTION_NUMBERS_ACTION_ID = 'action_question_numbers';
const GAME_DURATION_ACTION_ID = 'action_game_duration';
const CHANNEL_BLOCK_ID = 'dropdown_channel_id';
const QUESTION_NUMBERS_BLOCK_ID = 'dropdown_question_number';
const GAME_DURATION_BLOCK_ID = 'dropdown_game_duration';
const EMOJI_INPUT_SUBMISSION_ACTION_ID = 'sl_input';
const LETTERS_INPUT_SUBMISSION_ACTION_ID = 'sl_input';

const CHANNEL_DROPDOWN_DEFAULT = 'random';
const WELCOME_MSG_TIME_IN_SEC = 60;
const EMOJI_NUMBER_OF_QUESTIONS_OPTIONS = ['3', '5', '10'];
const EMOJI_GAME_DURATION_OPTIONS = ['5', '10', '15', '20'];
const LETTERS_GAME_DURATION_OPTIONS = ['5', '10', '15'];
const EMOJI_JARO_WINKLER_THRESHOLD = 0.863;

module.exports = {
  HOME_VIEW_HANDLER_EVENT_ID,
  FEEDBACK_BTN_HANDLER_ACTION_ID,
  HOME_EMOJI_BTN_HANDLER_ACTION_ID,
  HOME_LETTERS_BTN_HANDLER_ACTION_ID,
  TRIGGER_EMOJI_MODAL_CALLBACK_ID,
  TRIGGER_LETTERS_MODAL_CALLBACK_ID,
  HAPPY_HOURS_SLASH_COMMAND_ID,
  EMOJI_GUESS_BUTTON_ACTION_ID,
  EMOJI_GUESS_MODAL_SUBMISSION_CALLBACK_ID,
  INVITE_APP_TO_CHANNEL_ACTION_ID,
  ADD_APP_TO_CHANNEL_CALLBACK_ID,
  SHORTCUT_EMOJI_CALLBACK_ID,
  SHORTCUT_LETTERS_CALLBACK_ID,
  WELCOME_MSG_TIME_IN_SEC,
  EMOJI_NUMBER_OF_QUESTIONS_OPTIONS,
  EMOJI_GAME_DURATION_OPTIONS,
  EMOJI_INPUT_SUBMISSION_ACTION_ID,
  LETTERS_ANSWER_BUTTON_ACTION_ID,
  LETTERS_GAME_DURATION_OPTIONS,
  EMOJI_JARO_WINKLER_THRESHOLD,
  CHANNEL_DROPDOWN_DEFAULT,
  CHANNEL_ACTION_ID,
  QUESTION_NUMBERS_ACTION_ID,
  GAME_DURATION_ACTION_ID,
  CHANNEL_BLOCK_ID,
  QUESTION_NUMBERS_BLOCK_ID,
  GAME_DURATION_BLOCK_ID,
  GAME_STATUS_CREATED,
  GAME_STATUS_COMPLETED,
  GAME_TYPE_EMOJI,
  GAME_TYPE_LETTERS,
  LETTERS_INPUT_SUBMISSION_ACTION_ID,
  LETTERS_ANSWER_MODAL_SUBMISSION_CALLBACK_ID,
};
